### ISSUE TITLE
What is the akashjs equivalent of `provider-services lease-status`

### ISSUE THREAD

**Issue by debrisapron** [akash-network/akashjs#100]
Hiya, trying to write a script in akashjs that gets the URIs for a lease. As a reminder the Akash CLI invocation for this looks like:

```
provider-services lease-status --dseq $AKASH_DSEQ --from $AKASH_KEY_NAME --provider $AKASH_PROVIDER
```

Which returns a response like this:
```
{
  "services": {
    "web": {
      "name": "web",
      "available": 1,
      "total": 1,
      "uris": [
        "rga3h05jetf9h3p6dbk62m19ck.ingress.ewr1p0.mainnet.akashian.io"
      ],
      "observed_generation": 1,
      "replicas": 1,
      "updated_replicas": 1,
      "ready_replicas": 1,
      "available_replicas": 1
    }
  },
  "forwarded_ports": {}
}
```

However, the `get_lease_status.ts` example does not return any services information at all. There is a function in the `create_deployment.ts` example called `queryLeaseStatus` which I thought would do the job, but that doesn't seem to work either - I get an `UNABLE_TO_GET_ISSUER_CERT` every time. Is there a third method I should be trying?

**Comment by baktun14** [comment]
Hi, I believe this example this is the example you're referring to? https://github.com/akash-network/akashjs/blob/5db497dfcc23bd7982ef90864a780eea2220ab85/examples/create_deployment.ts#L244

**Comment by debrisapron** [comment]
Yeah that's the one. Always returns `UNABLE_TO_GET_ISSUER_CERT` for me.

**Comment by debrisapron** [comment]
Closing this because it's actually a bug in the `node:https` API in Bun! For anyone who cares, here's the issue: https://github.com/oven-sh/bun/issues/8616

**Comment by baktun14** [comment]
@debrisapron Thanks for the clarification! Can't wait for bun to be on feature parity with node.
