### ISSUE TITLE
Fix certificate generation

### ISSUE THREAD

**Issue by baktun14** [akash-network/akashjs#76]
Problem statement:
- In Cloudmos we have our own certificate generation which has been working for many years without issues: https://github.com/akash-network/cloudmos/blob/main/deploy-web/src/utils/certificateUtils.ts
- We need to merge or replace the code here: https://github.com/akash-network/akashjs/blob/main/src/certificates/generate509.ts

An error from a user:
- "TypeError: Cannot read properties of undefined (reading 'Integer')" , at createCSR function of /node_modules/@akashnetwork/akashjs/build/certificates/generate509.js:39:46
- Cannot read properties of null (reading 'getAlgorithmParameters')
const cert = await createCertificate(address);

TODO:
- [ ] Merge/replace certificate generation code into AkashJS
- [ ] Add tests

**Comment by Charizard13** [comment]
Any updates? or a workaournd for now?

**Comment by ygrishajev** [comment]
@Charizard13 [this](https://github.com/akash-network/akashjs/commit/5bb78af350f4f609424506e9b5fbe0f8a958d85b) should fix the issue. We're still working to sync implementation with akash-network/cloudmos
