### ISSUE TITLE
Lease status example `get_lease_status.ts` fails with `unknown query path: unknown request`

### ISSUE THREAD

**Issue by debrisapron** [akash-network/akashjs#96]
Filled in all the fields in the example but I get the above mentioned error. The `get_deployments` example works fine for me so I'm not sure what's wrong. I also don't really understand how the example is supposed to work - in the CLI `provider-services lease-status` needs your private key to run but this example doesn't include any credentials.

**Comment by baktun14** [comment]
Hi, can you provide a snippet of the code you have to query the lease status please? Also which version do you use?

**Comment by anilmurty** [comment]
hey @debrisapron - couple additional questions to help us debug:
1. Are you integrating your application for deploying on akash, using the examples under https://github.com/akash-network/akashjs/tree/main/examples?
2. Were you able to confirm being able to query the lease using the CLI?

**Comment by debrisapron** [comment]
Hi guys, thanks for getting back to me. So the lease status code is literally just copied & pasted from the example at https://github.com/akash-network/akashjs/blob/main/examples/get_lease_status.ts - all I did was set the node, owner, provider & dseq. The akashjs version is 0.10.0, the node is `https://rpc.akashnet.net:443` and the provider is `provider.a100.mon.obl.akash.pub`. Just checked it and I still get the same response, `unknown query path: unknown request`. I'm running the examples using bun 1.1.12.

A couple of extra things to note:
- Like I said [this example](https://github.com/akash-network/akashjs/blob/main/examples/get_deployments.ts) works perfectly with the same node & owner.
- I don't have any Akash-specific environment variables set.
- I get the same "unknown request" error if I change the dseq to a nonexistent one, so it seems like it's basically 404-ing?

**Comment by debrisapron** [comment]
Here's the failing source code for completeness:
```
import {
  QueryClientImpl,
  QueryLeaseRequest,
  QueryLeaseResponse,
} from "@akashnetwork/akash-api/akash/market/v1beta3"
import { getRpc } from "@akashnetwork/akashjs/build/rpc"

async function main() {
  const client = new QueryClientImpl(
    await getRpc("https://rpc.akashnet.net:443")
  )

  const getLeaseStatusRequest = QueryLeaseRequest.fromPartial({
    id: {
      owner: "akash120y40xuu5yrzeks89zlpwtkdj49n9mdn7dczts", // this is fake btw, DM me for the real one
      provider: "akash1tfuvntkwt3cpxnhukdnsvvsumjnrvmvh244l3w",
      dseq: 123456789, // fake deployment dseq, see above
      gseq: 1, // most of the time the value is 1
      oseq: 1, // most of the time the value is 1
    },
  })

  const leaseStatusResponse = await client.Lease(getLeaseStatusRequest)
  const data = QueryLeaseResponse.toJSON(leaseStatusResponse)

  console.log(data)
}

main()
```

**Comment by anilmurty** [comment]
Thanks @debrisapron - I assume you can see the lease status in https://console.akash.network/ as well? 

Tagging @ygrishajev who may be most familiar with the last change (to the API used https://github.com/akash-network/akashjs/commit/c708994f474ab2d440370a8fd1d73f11a1e2dcdb#diff-dec1ed0e0f468a91fa7bee7c86e35565eae8f231495ab5b0fe0241983170ae77)

**Comment by baktun14** [comment]
Thanks for the details @debrisapron . What are you guys trying to build with akashjs?

**Comment by ygrishajev** [comment]
hey @debrisapron thanks for rising this issue. As it appeared the example is outdated. Just opened a [pr](https://github.com/akash-network/akashjs/pull/97/files) to fix this. Could you pls try that and let me know if it fixes the issue?

**Comment by debrisapron** [comment]
That fixed it lol. Thank you so much!
